##version: "3"
##services:
##  sonarqube:
##    image: sonarqube:latest
##    ports:
##      - 9000:9000
##    environment:
##      - SONAR_FORCEAUTHENTICATION=false
#
#version: '3'
#services:
#  mysqldb:
##    image: mariadb:latest
#    image: mysql
#    container_name: database-container
#    environment:
##      MYSQL_USER: root
#      MYSQL_ROOT_PASSWORD: 12345678
#      MYSQL_DATABASE: testjpanew4
#    ports:
#      - 3307:3306
#
#  s3-individual:
#    image: s3-individual:latest
#    container_name: s3-individual-backend
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    depends_on:
##      - db
#      - mysqldb
#    environment:
##      MYSQL-HOST: database-container
#      MYSQL-HOST: mysqldb
#      USER: root
#      PASSWORD: 12345678
#      PORT: 3307
##      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
#    restart: always
#
#  app-client:
#    build:
#      dockerfile: Dockerfile
#      args:
#                REACT_APP_API_BASE_URL: https://127.0.0.1:8080
#    restart: always
#    depends_on:
#      -   s3-individual

version: '2'
services:
  mysqldb:
    image: mysql
    ports:
      - 3030:3306
    environment:
      MYSQL_DATABASE: hovno
      MYSQL_ROOT_PASSWORD: 1234qwerty

  s3app:
    build:
      dockerfile: Dockerfile
    image: backendimage:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234qwerty
      MYSQL_PORT: 3306
      # SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/s3restaurant?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
#
  app-client:
    build:
      context: ../stu.co/  # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "3000:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
    image: frontendimage:latest

    restart: always
    depends_on:
      - s3app
